apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-historical
  labels:
    app: service-historical
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-historical
  template:
    metadata:
      labels:
        app: service-historical
    spec:
      containers:
      - name: service-historical
        image: alugo81/ms-historical-v1
        args: ["--spring.profiles.active=dev","--spring.cloud.config.uri=http://54.86.107.127:8888"]
        ports:
        - containerPort: 8082
---
kind: Service
apiVersion: v1
metadata:
  name: app-service-historical
spec:
  type: LoadBalancer
  selector:
    app: service-historical
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8082