apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-nginx
  labels:
    app: service-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-nginx
  template:
    metadata:
      labels:
        app: service-nginx
    spec:
      containers:
      - name: service-nginx
        image: alugo81/ms-nginx-v1
        ports:
        - containerPort: 8085
---
kind: Service
apiVersion: v1
metadata:
  name: app-service-nginx
spec:
  type: LoadBalancer
  selector:
    app: service-nginx
  ports:
  - protocol: TCP
    port: 8095
    targetPort: 8085